# 수치미분
### 미분 
- 접점의 기울기
- 입력값이 변할 때 출력값이 얼마나 변하는지 알 수 있음
- 출력값은 입력값의 변화에 얼마나 민감하게 반응하는지 알 수 있음
- 예시) f(3) = 9 : 입력 x=3에서 출력은 9이다 
- f'(3) = 6 : 입력 x=3을 미세하게 변화시킬 때 함수는 현재 입력값의 2배인 6배의 변화를 일으킴

### 편미분
- 입력변수가 하나 이상인 다변수 함수에서 미분하고자 하는 변수 하나를 제외한 나머지 변수들을 상수로 취급하고 해당 변수를 미분하는 것


### 연쇄법칙 - Chain rule
- 합성함수란 여러 함수로 구성된 함수
- 합성함수를 미분하려면 합성함수를 구성하는 각 함수의 미분의 곱으로 나타내는 chain rule 이용

In [5]:
# 수치미분 구현 f'(x) = 2x
def numerical_derivative(f, x):
    delta_x= 1e-4
    return (f(x+delta_x) - f(x-delta_x))/ (2*delta_x)

def my_func1(x):

    return x**2

result = numerical_derivative(my_func1, 3)
print("result ==", result)  # 결과값은 x=3 일 때, 함수 f가 얼마나 변하는지를 나타냄

result == 6.000000000012662


In [7]:
# 수치미분 1차 버전
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

def numerical_Derivative(f, x):
    delta_x = 1e-4
    return (f(x+delta_x) - f(x-deleta_x)) / (2*delat_x)

result = numerical_derivative(my_func2, 2)
print("result ==", result)

print("실제 미분:", 3*np.exp(2) + 3*2*np.exp(2))

result == 66.50150507518049
실제 미분: 66.50150489037586


In [15]:
# 실제로 활용되는 수치미분
## 다 변수 함수의 경우 입력변수가 서로 독립적이기 때문에 수치미분 또한 변수의 개수만큼 개별적으로 계산함

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x) # 입력 파라미터 x와 동일한 크기를 가짐 (0으로 초기화하여 나중에 저장)
    
    # 순차적으로 데이터 읽기
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:  # 변수의 개수만큼 반복
        idx = it.multi_index
        
        tmp_val = x[idx]   # 원본값을 저장하는 임시변수가 반드시 필요!
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)  # f(x+delta_x)
        
        x[idx] = tmp_val = delta_x
        fx2 = f(x)  # f(x=delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

### debug를 넣어 값들의 출력을 확인 

In [28]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x) 
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================================")
   
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:  # 변수의 개수만큼 반복
        idx = it.multi_index
        
        print("debug 3. idx =", idx, ", x[idx] = ", x[idx])
        
        tmp_val = x[idx]   # 원본값을 저장하는 임시변수가 반드시 필요!
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)  # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)  # f(x=delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] =", grad[idx])
        print("debug 5. grad =", grad)
        print("=======================================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

### 1변수 함수: f(x) = x^2, f'(3.0)

In [29]:
def func1(input_obj):
    x = input_obj[0]
    
    return x**2

numerical_derivative(func1, np.array([3.0]) )

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx = (0,) , x[idx] =  3.0
debug 4. grad[idx] = 6.000000000012662
debug 5. grad = [6.]


array([6.])

### 2변수 함수 : f(x,y) = 2x + 3xy + y^3, f'(1.0, 2.0)

In [30]:
def func2(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))

input = np.array([1.0, 2.0])
numerical_derivative(func2, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx = (0,) , x[idx] =  1.0
debug 4. grad[idx] = 7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx = (1,) , x[idx] =  2.0
debug 4. grad[idx] = 15.000000010019221
debug 5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

### 4변수 함수 : f(w,x,y,z) = wx +xyz + 3w + zy^2, f'(1.0, 2.0, 3.0, 4.0)

In [31]:
def func3(input_obj):
    w = input_obj[0, 0]
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2) )

input = np.array([ [1.0, 2.0], [3.0, 4.0] ])
numerical_derivative(func3, input)
    

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx = (0, 0) , x[idx] =  1.0
debug 4. grad[idx] = 5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx = (0, 1) , x[idx] =  2.0
debug 4. grad[idx] = 13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx = (1, 0) , x[idx] =  3.0
debug 4. grad[idx] = 32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx = (1, 1) , x[idx] =  4.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])