# Numpy

## Numpy 라이브러리 활용
### 벡터, 행렬 등을 표현하고 연산할 때 사용하는 라이브러리
- vector/ matrix 생성
- 행렬 곱 (dot product) 
- broadcast
- index / slice/ iterator
- concatenate
- useful function (loadtxt(), rand(), argmax(), ...)

In [2]:
import numpy as np

A = np.array([1,2])
print("A ==", A, ", type ==", type(A))

from numpy import exp
result = exp(1)
print("result ==", result, "type ==", type(result))

A == [1 2] , type == <class 'numpy.ndarray'>
result == 2.718281828459045 type == <class 'numpy.float64'>


In [5]:
# 벡터(vector) 생성
A = np.array([1,2,3])
B = np.array([4,5,6])

# vector A, B 형상 출력 => shape
print("A.shape ==", A.shape, ",B.shape ==", B.shape)

# vecotr A, B 차원 출력 => ndim
print("A.ndim ==", A.ndim, ",B.ndim ==", B.ndim)

A.shape == (3,) ,B.shape == (3,)
A.ndim == 1 ,B.ndim == 1


In [7]:
# 행렬(matrix) 생성
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[-1,-2,-3], [-4,-5,-6]])

# matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape, ",B.shape ==", B.shape)

# matrix A, B 차원 출력 => ndim
print("A.ndim ==", A.ndim, ",B.ndim ==", B.ndim)

# 형 변환(reshape)
C = np.array([1,2,3])
C = C.reshape(1,3)

print("C.shape ==", C.shape)

A.shape == (2, 3) ,B.shape == (2, 3)
A.ndim == 2 ,B.ndim == 2
C.shape == (1, 3)


In [9]:
# 행렬 곱(dot product)
## 앞부분의 열과 뒷부분의 행이 같아야 함!
A = np.array([[1,2,3], [4,5,6]])  # 2X3
B = np.array([[-1,-2], [-3,-4] ,[-5,-6]]) # 3X2

C = np.dot(A, B)
print("C.shpae ==" , C.shape) # 2X2
print(C)

C.shpae == (2, 2)
[[-22 -28]
 [-49 -64]]


In [11]:
# numpy broadcast : 차원이 다른 두 행렬간도 사칙연산이 가능 (행렬곱에서는 안됨!!)
## 차원이 작은 쪽이 큰 쪽의 행단위로 반복적으로 크기를 맞춘 후 계산
A = np.array([[1,2], [3,4]])
b = 5
print(A+b)

c = np.array([4,5])
print(A+c)

[[6 7]
 [8 9]]
[[5 7]
 [7 9]]


In [20]:
# 전치행렬(transpose) : 원본 행렬이 열은 행으로 행은 열로 바꾼 것
A = np.array([[1,2], [3,4], [5,6]])
B = A.T
print("A.shape ==", A.shape, ",B.shape ==", B.shape)
print("A의 행렬:\n", A)
print("B의 행렬:\n", B)
print()
# 단 전치행렬은 vector는 안됨 
## why? vector는 열과 행을 구분하지 않기 때문
C = np.array([1,2,3,4,5])
D = C.T
print("C.shape ==", C.shape, ",D.shape ==", D.shape)
print("C의 행렬:\n", C)
print("D의 행렬:\n", D)

# reshape를 통해 변경 후 전치행렬 가능
E = C.reshape(1,5)
F = E.T
print()
print("E.shape ==", E.shape, ",F.shape ==", F.shape)
print("E의 행렬:\n", E)
print("F의 행렬:\n", F)

A.shape == (3, 2) ,B.shape == (2, 3)
A의 행렬:
 [[1 2]
 [3 4]
 [5 6]]
B의 행렬:
 [[1 3 5]
 [2 4 6]]

C.shape == (5,) ,D.shape == (5,)
C의 행렬:
 [1 2 3 4 5]
D의 행렬:
 [1 2 3 4 5]

E.shape == (1, 5) ,F.shape == (5, 1)
E의 행렬:
 [[1 2 3 4 5]]
F의 행렬:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [28]:
# indexing/ slicing 가능
A = np.array([10,20,30,40,50,60]).reshape(3,2)

print(A)
print("A[0,0] ==", A[0,0])
print("A[0:-1, 1:2] ==", A[0:-1, 1:1])
print("A[:,0] ==", A[:,0])
print()

# iterator: 순차적으로 데이터 값을 읽기 가능
A = np.array([[10,20,30,40], [50,60,70,80]])
print("A:",A,"\n")
print("A.shape ==", A.shape)
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print("current value =>", A[idx])
    it.iternext()

[[10 20]
 [30 40]
 [50 60]]
A[0,0] == 10
A[0:-1, 1:2] == []
A[:,0] == [10 30 50]

A: [[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4)
current value => 10
current value => 20
current value => 30
current value => 40
current value => 50
current value => 60
current value => 70
current value => 80


In [34]:
# concatenate : 기존 행렬에 행이나 열 추가 가능

A = np.array([[20,30,40], [50,60,70]])
print(A.shape)
print(A,"\n")

# 하나의 vector는 reshape을 통해 행렬로 변경 후 concatenate 진행
row_add = np.array([80,90,100]).reshape(1,3)

column_add = np.array([1000, 2000]).reshape(2,1)

B = np.concatenate((A, row_add), axis = 0)
print(B)

C = np.concatenate((A, column_add), axis=1)
print(C)

(2, 3)
[[20 30 40]
 [50 60 70]] 

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]
[[  20   30   40 1000]
 [  50   60   70 2000]]


In [44]:
# loadtxt : 구분된 파일에서 데이터를 읽기 위해 사용
## 머신러닝 코드에서 입력데이터와 정답데이터를 분리하는 프로그래밍 기법


# rand : 0~1 사이의 random number 발생
random_number1 = np.random.rand(3)
random_number2 = np.random.rand(1,3)
print("random_number1 ==", random_number1, ",random_number1.shape ==", random_number1.shape)
print("random_number2 ==", random_number2, ",random_number2.shape ==", random_number2.shape)

# sum, exp, log
X = np.array([2,4,6,8])
print("np.sum(X) ==", np.sum(X))
print("np.exp(X) ==", np.exp(X))
print("np.log(X) ==", np.log(X))
print()

# max. min, argmax, argmin
print("np.max(X) ==", np.max(X))
print("np.min(X) ==", np.min(X))
print("np.argmax(X) ==", np.argmax(X)) # 최대값이 있는 인덱스를 리턴
print("np.argmax(X) ==", np.argmin(X)) # 최솟값이 있는 인덱스를 리턴
print()

X = np.array([[2,4,6], [1,2,3], [0,5,8]])
print(X)
print("np.max(X) ==", np.max(X, axis= 0)) # axis = 0, 열 기준
print("np.max(X) ==", np.max(X, axis= 1)) # axis = 1, 행 기준
print("np.argmax(X) ==", np.argmax(X, axis= 0)) # 열 기준 가장 큰 값의 인덱스 값
print("np.argmax(X) ==", np.argmax(X, axis= 1))

# ones : 1로 값을 채워주는 것
# zeros : 0의 값으로 채워주는 것

random_number1 == [0.58506287 0.32169524 0.2364428 ] ,random_number1.shape == (3,)
random_number2 == [[0.53344788 0.03772381 0.22119099]] ,random_number2.shape == (1, 3)
np.sum(X) == 20
np.exp(X) == [   7.3890561    54.59815003  403.42879349 2980.95798704]
np.log(X) == [0.69314718 1.38629436 1.79175947 2.07944154]

np.max(X) == 8
np.min(X) == 2
np.argmax(X) == 3
np.argmax(X) == 0

[[2 4 6]
 [1 2 3]
 [0 5 8]]
np.max(X) == [2 5 8]
np.max(X) == [6 3 8]
np.argmax(X) == [0 2 2]
np.argmax(X) == [2 2 2]
